#coding: utf-8
# C++ 目标代码生成器

import uuid

import common

class CPlusPlus:
    def __init__(self, schema, sqlgen, namespace):
        self.sqlgen = sqlgen
        self.schema = schema
        self.namespace = namespace


    def Generate(self):
        print self._Header()

        for database in self.schema['databases']:
            print self._GenDatabase(database)

        print self._Footer()


    def _GenDatabase(self, db_idl):
        print self.sqlgen.CreateDatabaseSQL(db_idl)
        for table in db_idl['tables']:
            print self.sqlgen.CreateTableSQL(table)


    def _Header(self):
        h = '''// Generated by SQLess v$VERSION
// project homepage http://www.sqless.org

#ifndef SQLESS_$UUID_H
#define SQLESS_$UUID_H

#include <string>
#include <vector>
        '''
        h = h.replace('$VERSION', common.Version())
        h = h.replace('$UUID', str(uuid.uuid1()))

        h += '\n' + self.sqlgen.Header();

        if self.namespace:
            h += '\n\nnamespace ' + self.namespace + ' {\n'

        return h


    def _Footer(self):
        f= '\n\n'

        if self.namespace:
            f += '} // namespace ' + self.namespace + '\n\n'

        f += '#endif\n'

        return f

